---
title: "Mediation Analysis for Microbiome Data"
author: "Giulio Benedetti"
editor: visual
---

```{r}
#| label: setup
#| include: FALSE

# Import utilities
source("funs.R")

# Set chunks options
knitr::opts_chunk$set(warning = FALSE)
```

## Dataset 1

```{r}
#| label: import-data1
#| message: FALSE
tse <- LahtiWAData()
```

```{r}
#| label: prepare-data1
colData(tse)$bmi_group <- as.numeric(tse$bmi_group)

tse2 <- tse[ , !is.na(tse$bmi_group)]
tse2 <- tse2[ , !is.na(tse2$nationality)]

tse2 <- tse[ , tse$nationality %in% c("CentralEurope", "Scandinavia")]
colData(tse2)$nationality <- as.numeric(factor(tse2$nationality)) - 1
```

### Mediation of alpha diversity

```{r}
#| label: alpha-mediation1
med_out <- mediate_coldata(tse,
                           outcome = "bmi_group",
                           treatment = "nationality",
                           mediator = "diversity",
                           covariates = c("sex", "age"),
                           treat.value = "Scandinavia",
                           control.value = "CentralEurope",
                           boot = TRUE, sims = 100)

summary(med_out)
```

```{r}
#| label: plt-alpha1
plot(med_out)
```

### Mediation of microbiome assay

```{r}
#| label: assay-mediation1
tse <- transformAssay(tse2,
                      method = "clr",
                      pseudocount = 1)

hdma_res <- mediate_hdma(A = tse$nationality,
                         M = t(assay(tse, "clr")),
                         Y = tse$bmi_group)
```

```{r}
#| label: assay-effects1
hdma_res$effects %>% knitr::kable()
```

```{r}
#| label: assay-contributions1
hdma_res$contributions %>% 
  filter(ab_pv < 0.05) %>%
  knitr::kable()
```

## Dataset 2

```{r}
#| label: import-data2
#| message: FALSE
tse <- OKeefeDSData()
```

```{r}
#| label: prepare-data2
tse <- transformAssay(tse,
                      method = "relabundance")

tse <- estimateDiversity(tse,
                         index = "shannon",
                         assay.type = "relabundance")
```

```{r}
#| label: prepare-data3
colData(tse)$bmi_group <- as.numeric(tse$bmi_group)

tse2 <- tse[ , !is.na(tse$bmi_group)]
tse2 <- tse2[ , !is.na(tse2$nationality)]

tse2 <- tse[ , tse$nationality %in% c("CentralEurope", "Scandinavia")]
colData(tse2)$nationality <- as.numeric(factor(tse2$nationality)) - 1
```

### Mediation of alpha diversity

```{r}
#| label: alpha-mediation2
med_out <- mediate_coldata(tse,
                           outcome = "bmi_group",
                           treatment = "nationality",
                           mediator = "shannon",
                           covariates = "timepoint.within.group",
                           boot = TRUE, sims = 1000)

summary(med_out)
```

```{r}
#| label: plt-alpha2
plot(med_out)
```

### Mediation of microbiome assay

```{r}
#| label: mediation-assay2
tse <- transformAssay(tse2,
                      method = "clr",
                      pseudocount = 1)

hdma_res <- mediate_hdma(A = tse$nationality,
                         M = t(assay(tse, "clr")),
                         Y = tse$bmi_group,
                         C1 = matrix(tse$timepoint.within.group))
```

```{r}
#| label: assay-effects2
hdma_res$effects %>% knitr::kable()
```

```{r}
#| label: assay-contributions2
hdma_res$contributions %>% 
  filter(ab_pv < 0.05) %>%
  knitr::kable()
```
